<?php

namespace AddressBoxBundle\Repository;

/**
 * TelefonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefonRepository extends \Doctrine\ORM\EntityRepository
{
}
