<?php

namespace AddressBoxBundle\Repository;

/**
 * AdresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresRepository extends \Doctrine\ORM\EntityRepository
{
}
