<?php

namespace AddressBoxBundle\Repository;

/**
 * OsobaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsobaRepository extends \Doctrine\ORM\EntityRepository
{
}
