<?php

namespace Proxies\__CG__\AddressBoxBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Osoba extends \AddressBoxBundle\Entity\Osoba implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'id', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'imie', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'nazwisko', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'opis', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'adres', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'telefony', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'emaile'];
        }

        return ['__isInitialized__', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'id', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'imie', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'nazwisko', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'opis', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'adres', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'telefony', '' . "\0" . 'AddressBoxBundle\\Entity\\Osoba' . "\0" . 'emaile'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Osoba $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setImie($imie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImie', [$imie]);

        return parent::setImie($imie);
    }

    /**
     * {@inheritDoc}
     */
    public function getImie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImie', []);

        return parent::getImie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNazwisko($nazwisko)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNazwisko', [$nazwisko]);

        return parent::setNazwisko($nazwisko);
    }

    /**
     * {@inheritDoc}
     */
    public function getNazwisko()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNazwisko', []);

        return parent::getNazwisko();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpis($opis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpis', [$opis]);

        return parent::setOpis($opis);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpis', []);

        return parent::getOpis();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdres(\AddressBoxBundle\Entity\Adres $adres = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdres', [$adres]);

        return parent::setAdres($adres);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdres', []);

        return parent::getAdres();
    }

    /**
     * {@inheritDoc}
     */
    public function addTelefony(\AddressBoxBundle\Entity\Telefon $telefony)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTelefony', [$telefony]);

        return parent::addTelefony($telefony);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTelefony(\AddressBoxBundle\Entity\Telefon $telefony)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTelefony', [$telefony]);

        return parent::removeTelefony($telefony);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefony()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefony', []);

        return parent::getTelefony();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmaile(\AddressBoxBundle\Entity\Email $emaile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmaile', [$emaile]);

        return parent::addEmaile($emaile);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmaile(\AddressBoxBundle\Entity\Email $emaile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmaile', [$emaile]);

        return parent::removeEmaile($emaile);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmaile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmaile', []);

        return parent::getEmaile();
    }

    /**
     * {@inheritDoc}
     */
    public function getImieNazwisko()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImieNazwisko', []);

        return parent::getImieNazwisko();
    }

}
